/**
 * 句動詞の「意味を固定する目的語」。
 *
 * 句動詞は単体では多義で、`take in` だけを見せられても「摂取する」なのか
 * 「理解する」なのか「だます」なのか決まらない。頻出の目的語を隣に置くと
 * 意味が一つにピン留めされ、丸暗記ではなくコアイメージからの推測が働く。
 *
 * ここに書くのは「動詞句の後ろに続く語」だけ。表示は `${target} [${値}]`、
 * 読み上げは `${target} ${値}` になる。
 *
 * 【書くときの約束】
 * - その語彙項目に登録済みの answers の語義に合わせること。
 *   表示された目的語と、正解として受理される訳がズレると学習の邪魔になる。
 * - 自動詞など、後ろに自然な語が続かない句動詞は**書かない**。
 *   このフィールドは任意で、無い項目は今までどおり単体で出題される。
 * - キーは lib/vocab/wordId.ts の安定ID。target を書き換えるとIDが変わり
 *   既存ユーザーの統計が失われるため、目的語は target に混ぜないこと。
 */
export const COLLOCATIONS: Readonly<Record<string, string>> = {
  "abide-by:phrase": "the rules",
  "abound-in:phrase": "natural resources",
  "act-on:phrase": "the proposal",
  "add-up-to:phrase": "a big problem",
  "adhere-to:phrase": "the rules",
  "air-out:phrase": "the room",
  "allow-for:phrase": "delays",
  "back-down:phrase": "from the demand",
  "back-off:phrase": "from the argument",
  "back-up:phrase": "your claim",
  "bail-out:phrase": "the bank",
  "bank-on:phrase": "his support",
  "bargain-for:phrase": "a lower price",
  "barge-in:phrase": "on the meeting",
  "bear-down:phrase": "on the enemy",
  "believe-in:phrase": "yourself",
  "blend-in:phrase": "with the crowd",
  "boil-down-to:phrase": "one question",
  "bounce-back:phrase": "from the loss",
  "bow-out:phrase": "of the race",
  "bowl-over:phrase": "the audience",
  "branch-out:phrase": "into new markets",
  "break-down:phrase": "the door",
  "break-in:phrase": "through the window",
  "bring-about:phrase": "change",
  "bring-off:phrase": "the deal",
  "bring-on:phrase": "a headache",
  "bring-out:phrase": "the best in him",
  "brush-off:phrase": "the criticism",
  "buckle-down:phrase": "to work",
  "buck-for:phrase": "a promotion",
  "build-up:phrase": "a reputation",
  "buy-over:phrase": "an official",
  "buy-up:phrase": "all the tickets",
  "call-off:phrase": "the meeting",
  "call-on:phrase": "a client",
  "capitalize-on:phrase": "the opportunity",
  "carry-out:phrase": "the plan",
  "carry-through:phrase": "the reform",
  "cast-away:phrase": "doubts",
  "cast-off:phrase": "old clothes",
  "catch-up:phrase": "with the others",
  "cheat-on:phrase": "the exam",
  "chip-in:phrase": "for the gift",
  "cling-to:phrase": "hope",
  "come-across:phrase": "an old photo",
  "come-around:phrase": "to my place",
  "come-down-to:phrase": "money",
  "come-down-with:phrasal-verb": "a cold",
  "conflict-with:phrase": "my schedule",
  "conform-to:phrase": "the rules",
  "confess-to:phrase": "the crime",
  "contend-with:phrase": "heavy traffic",
  "contribute-to:phrase": "the project",
  "cope-with:phrase": "stress",
  "cough-up:phrase": "the money",
  "count-for:phrase": "nothing",
  "count-on:phrase": "your help",
  "cover-for:phrase": "a colleague",
  "cross-out:phrase": "the word",
  "cross-over:phrase": "the bridge",
  "cut-back-on:phrase": "spending",
  "cut-down:phrase": "expenses",
  "cut-off:phrase": "the water supply",
  "deal-with:phrase": "the problem",
  "dish-out:phrase": "the food",
  "do-away-with:phrasal-verb": "the rule",
  "doze-off:phrase": "in class",
  "drag-on:phrase": "for hours",
  "drive-off:phrase": "the intruder",
  "drop-by:phrase": "the office",
  "drop-off:phrase": "a package",
  "drum-up:phrase": "support",
  "ease-into:phrase": "the new role",
  "eat-up:phrase": "the leftovers",
  "edge-out:phrase": "a rival",
  "embroil-in:phrase": "a scandal",
  "end-up:phrasal-verb": "in debt",
  "end-up-with:phrase": "a huge bill",
  "experiment-with:phrase": "new methods",
  "face-off:phrase": "against the champion",
  "fall-back-on:phrase": "savings",
  "fall-in-with:phrase": "a bad crowd",
  "fall-into:phrase": "two categories",
  "fall-off:phrase": "sharply",
  "fall-under:phrase": "this category",
  "feel-for:phrase": "the victims",
  "feed-on:phrase": "insects",
  "fell-for:phrasal-verb": "the scam",
  "fight-back:phrase": "against the attack",
  "figure-out:phrase": "the answer",
  "fill-out:phrase": "the form",
  "finish-off:phrase": "the report",
  "fire-up:phrase": "the engine",
  "fish-for:phrase": "compliments",
  "fit-in:phrase": "with the group",
  "fit-into:phrase": "the team",
  "force-down:phrase": "the medicine",
  "frown-upon:phrase": "such behavior",
  "get-away-with:phrase": "the money",
  "get-by:phrase": "on a small salary",
  "get-down-to:phrase": "business",
  "get-in-on:phrase": "the deal",
  "get-into:phrase": "a good university",
  "get-on-with:phrase": "his colleagues",
  "get-past:phrasal-verb": "the gate",
  "give-away:phrase": "free samples",
  "give-in:phrase": "to pressure",
  "give-off:phrase": "a strange smell",
  "give-over:phrase": "control",
  "go-against:phrase": "the rules",
  "go-back-on:phrase": "a promise",
  "go-over:phrase": "the details",
  "grow-into:phrase": "a serious problem",
  "gun-for:phrase": "the top job",
  "hand-off:phrase": "the task",
  "hang-around:phrase": "the station",
  "hang-on:phrasal-verb": "to the rope",
  "hang-on-to:phrase": "your receipt",
  "hang-out:phrase": "with friends",
  "hang-up:phrase": "the phone",
  "head-off:phrase": "a crisis",
  "head-out:phrase": "for the airport",
  "hold-off:phrase": "the attack",
  "hold-over:phrase": "the decision",
  "hold-up:phrase": "under pressure",
  "infringe-on:phrase": "their rights",
  "inquire-after:phrase": "his health",
  "invest-in:phrase": "real estate",
  "iron-out:phrase": "the differences",
  "jack-up:phrase": "the price",
  "keep-down:phrase": "your voice",
  "keep-up-on:phrase": "the news",
  "keep-up-with:phrase": "the class",
  "kick-off:phrase": "the campaign",
  "knock-down:phrasal-verb": "the old building",
  "lay-down:phrase": "your weapons",
  "lay-off:phrasal-verb": "workers",
  "let-on:phrase": "the secret",
  "let-out:phrase": "the dog",
  "live-up-to:phrase": "expectations",
  "lock-in:phrase": "the heat",
  "look-down-on:phrase": "others",
  "look-into:phrase": "the cause",
  "look-over:phrase": "the contract",
  "look-to:phrase": "the government",
  "look-up-to:phrasal-verb": "my mentor",
  "lose-out-to:phrase": "a rival",
  "make-out:phrase": "his handwriting",
  "make-over:phrase": "the kitchen",
  "mapped-out:phrasal-verb": "a route",
  "mingle-with:phrase": "the guests",
  "miss-out:phrase": "on the chance",
  "nod-off:phrase": "during the lecture",
  "opt-for:phrase": "the cheaper plan",
  "pack-up:phrase": "your things",
  "pass-for:phrase": "a native speaker",
  "pass-on:phrase": "the message",
  "pass-out:phrase": "from the heat",
  "pass-over:phrase": "his mistake",
  "pass-through:phrase": "the tunnel",
  "pay-down:phrase": "the debt",
  "pay-off:phrase": "the loan",
  "peel-away:phrase": "the sticker",
  "pertain-to:phrase": "the case",
  "phase-out:phrasal-verb": "old models",
  "pick-over:phrase": "the fruit",
  "pick-through:phrase": "the rubble",
  "pile-in:phrase": "to the car",
  "pile-up:phrase": "debts",
  "pin-down:phrase": "the suspect",
  "play-down:phrase": "the risk",
  "point-out:phrase": "the mistake",
  "pop-up:phrase": "on the screen",
  "pore-over:phrase": "the documents",
  "prop-up:phrase": "the fence",
  "pull-in:phrase": "at the station",
  "pull-over:phrase": "to the shoulder",
  "pull-through:phrase": "the illness",
  "push-through:phrase": "the bill",
  "read-off:phrase": "the numbers",
  "rebel-against:phrase": "authority",
  "register-for:phrase": "a course",
  "rely-on:phrase": "his advice",
  "rest-on:phrase": "an assumption",
  "roll-up:phrase": "your sleeves",
  "root-out:phrase": "corruption",
  "rough-up:phrase": "the suspect",
  "round-up:phrase": "the cattle",
  "rub-in:phrase": "the cream",
  "rule-out:phrase": "the possibility",
  "scoop-up:phrase": "the sand",
  "scratch-out:phrase": "a name",
  "see-out:phrase": "a guest",
  "see-through:phrase": "his lies",
  "send-in:phrase": "an application",
  "send-out-for:phrase": "pizza",
  "set-aside:phrase": "some money",
  "set-off:phrase": "an alarm",
  "settle-up:phrase": "the bill",
  "sew-up:phrase": "the wound",
  "shake-up:phrase": "the company",
  "show-off:phrase": "his new car",
  "show-up:phrase": "at the party",
  "shut-out:phrase": "the noise",
  "sign-up:phrase": "for the class",
  "sit-up:phrase": "late",
  "skim-over:phrase": "the report",
  "sleep-over:phrase": "at a friend's house",
  "smooth-over:phrase": "the dispute",
  "sort-out:phrase": "the papers",
  "speak-for:phrase": "the group",
  "specialize-in:phrase": "tax law",
  "split-up:phrase": "the group",
  "stand-down:phrase": "as chairman",
  "stand-out:phrase": "in the crowd",
  "stand-over:phrase": "the workers",
  "stand-up-to:phrase": "a bully",
  "stay-off:phrase": "the grass",
  "step-down:phrase": "as CEO",
  "stick-around:phrase": "for a while",
  "stick-to:phrase": "the wall",
  "stick-up-for:phrase": "your friend",
  "stick-with:phrase": "the plan",
  "stir-up:phrase": "trouble",
  "stop-by:phrase": "the store",
  "stop-over:phrase": "in Dubai",
  "sum-up:phrase": "the findings",
  "swallow-up:phrase": "the savings",
  "take-after:phrase": "his father",
  "take-in:phrase": "nutrients",
  "take-on:phrase": "a new project",
  "take-over:phrase": "the business",
  "take-up:phrase": "the issue",
  "talk-back-to:phrase": "his teacher",
  "talk-down-to:phrase": "his staff",
  "talk-up:phrase": "the product",
  "tear-down:phrase": "the old house",
  "tear-off:phrase": "the label",
  "tell-on:phrase": "his classmate",
  "think-out:phrase": "a plan",
  "throw-off:phrase": "his coat",
  "throw-up:phrase": "his lunch",
  "tide-over:phrase": "the crisis",
  "tidy-up:phrase": "the room",
  "tie-up:phrase": "the boat",
  "tighten-up:phrase": "security",
  "track-down:phrase": "the suspect",
  "trade-in:phrase": "an old car",
  "trifle-with:phrase": "his feelings",
  "try-out:phrase": "a new recipe",
  "tune-up:phrase": "the engine",
  "turn-down:phrase": "the offer",
  "turn-over:phrase": "the pancake",
  "want-for:phrase": "nothing",
  "wash-away:phrase": "the soil",
  "water-down:phrasal-verb": "the proposal",
  "weed-out:phrase": "weak candidates",
  "weigh-on:phrase": "his mind",
  "win-over:phrase": "the voters",
  "wind-up:phrase": "the meeting",
  "wipe-up:phrase": "the spill",
  "work-off:phrase": "the debt",
  "work-out:phrase": "at the gym",
  "wrap-up:phrase": "the meeting",
  "wrestle-with:phrase": "the problem",
};
