import type { ComposePrompt } from "../types";

/**
 * レベル3（応用）。
 *
 * 節が2つ以上、あるいは日本語と英語で発想の転換が必要な問題。
 * 直訳では通らないので、AI採点の添削がいちばん効く層でもある。
 */
export const ADVANCED_PROMPTS: ComposePrompt[] = [
  {
    id: "a01",
    ja: "私が電話したとき、彼はちょうど出かけるところでした。",
    answers: [
      "He was about to go out when I called him.",
      "When I called him, he was just about to leave.",
    ],
    tags: ["tense", "progressive"],
    level: 3,
    note: "「〜するところだった」は be about to do。",
  },
  {
    id: "a02",
    ja: "もっと早くその問題に気づいていれば、こんなことにはならなかっただろう。",
    answers: [
      "If we had noticed the problem earlier, this would not have happened.",
      "If I had noticed the problem earlier, it would not have happened.",
    ],
    tags: ["conditional", "perfect"],
    level: 3,
    note: "過去の事実に反する仮定は If + had + 過去分詞 + would have + 過去分詞。",
  },
  {
    id: "a03",
    ja: "彼は英語で書かれた本を何冊も持っています。",
    answers: ["He has many books written in English.", "He owns several books written in English."],
    tags: ["participle", "passive"],
    level: 3,
    note: "受動の意味で名詞を後ろから説明するときは過去分詞。",
  },
  {
    id: "a04",
    ja: "駅で待っている間に、私はメールを何通か書きました。",
    answers: [
      "While I was waiting at the station, I wrote a few emails.",
      "Waiting at the station, I wrote a few emails.",
    ],
    tags: ["participle", "progressive", "quantifier"],
    level: 3,
    note: "a few + 可算名詞の複数形。分詞構文にもできる。",
  },
  {
    id: "a05",
    ja: "時間がなかったので、私たちはタクシーに乗りました。",
    answers: [
      "Since we had no time, we took a taxi.",
      "Having no time, we took a taxi.",
    ],
    tags: ["participle", "subordinate", "verb-choice"],
    level: 3,
    note: "タクシーに「乗る」は take a taxi。ride on とはしない。",
  },
  {
    id: "a06",
    ja: "彼が正直だということは誰もが知っています。",
    answers: [
      "Everyone knows that he is honest.",
      "It is well known that he is honest.",
    ],
    tags: ["subordinate", "formal-subject", "agreement"],
    level: 3,
    note: "everyone は単数扱い。形式主語 It is ... that でも書ける。",
  },
  {
    id: "a07",
    ja: "その規則は変えられるべきだと思います。",
    answers: ["I think the rule should be changed.", "I believe that the rule should be changed."],
    tags: ["passive", "modal", "subordinate"],
    level: 3,
    note: "should + be + 過去分詞。助動詞のあとは必ず原形。",
  },
  {
    id: "a08",
    ja: "値段を考えると、その品質には満足できません。",
    answers: [
      "Considering the price, I am not satisfied with the quality.",
      "Given the price, I'm not happy with the quality.",
    ],
    tags: ["participle", "passive", "prepositions"],
    level: 3,
    note: "「〜を考えると」は considering。be satisfied with の前置詞は with。",
  },
  {
    id: "a09",
    ja: "私は妹に部屋を片付けてもらいました。",
    answers: ["I had my sister clean the room.", "I got my sister to clean the room."],
    tags: ["causative"],
    level: 3,
    note: "have + 人 + 原形 / get + 人 + to do。形が違う。",
  },
  {
    id: "a10",
    ja: "彼は髪を切ってもらったばかりです。",
    answers: ["He has just had his hair cut.", "He just got his hair cut."],
    tags: ["causative", "perfect"],
    level: 3,
    note: "物・体の一部を「〜してもらう」は have + 物 + 過去分詞。",
  },
  {
    id: "a11",
    ja: "この機械は簡単に操作できるように設計されています。",
    answers: [
      "This machine is designed to be easy to operate.",
      "This machine is designed so that it can be operated easily.",
    ],
    tags: ["passive", "infinitive-gerund"],
    level: 3,
    note: "目的を表す to do と so that。受動態と組み合わせる。",
  },
  {
    id: "a12",
    ja: "彼女がその仕事を引き受けるかどうかは、まだ分かりません。",
    answers: [
      "It is not clear yet whether she will take the job.",
      "We don't know yet whether she will accept the job.",
    ],
    tags: ["formal-subject", "subordinate"],
    level: 3,
    note: "主語が長い「〜かどうかは」は形式主語 It で始める。",
  },
  {
    id: "a13",
    ja: "参加者の数は予想より多かった。",
    answers: [
      "The number of participants was larger than we had expected.",
      "The number of participants was bigger than expected.",
    ],
    tags: ["agreement", "comparison", "quantifier"],
    level: 3,
    note: "the number of + 複数名詞は単数扱い（was）。多い少ないは large / small。",
  },
  {
    id: "a14",
    ja: "彼は約束を守らなかったことを謝りました。",
    answers: [
      "He apologized for not keeping his promise.",
      "He apologized for breaking his promise.",
    ],
    tags: ["infinitive-gerund", "prepositions", "verb-choice"],
    level: 3,
    note: "apologize for + 動名詞。動名詞の否定は前に not を置く。",
  },
  {
    id: "a15",
    ja: "彼の説明は私にはまったく理解できませんでした。",
    answers: [
      "I could not understand his explanation at all.",
      "His explanation made no sense to me.",
    ],
    tags: ["modal", "verb-choice"],
    level: 3,
    note: "「まったく〜ない」は not ... at all。",
  },
  {
    id: "a16",
    ja: "駅に着いたら電話してください。",
    answers: ["Please call me when you get to the station.", "Call me when you arrive at the station."],
    tags: ["subordinate", "tense", "request"],
    level: 3,
    note: "when 節は未来でも現在形。arrive at / get to の前置詞に注意。",
  },
  {
    id: "a17",
    ja: "そんなことを言うなんて、彼は疲れていたに違いありません。",
    answers: [
      "He must have been tired to say such a thing.",
      "He must have been tired, or he wouldn't have said such a thing.",
    ],
    tags: ["modal", "perfect"],
    level: 3,
    note: "過去についての強い推量は must have + 過去分詞。",
  },
  {
    id: "a18",
    ja: "彼はもっと注意すべきでした。",
    answers: ["He should have been more careful.", "He ought to have been more careful."],
    tags: ["modal", "perfect", "comparison"],
    level: 3,
    note: "しなかったことへの後悔は should have + 過去分詞。",
  },
  {
    id: "a19",
    ja: "この本は初心者向けに書かれています。",
    answers: ["This book is written for beginners.", "This book was written for beginners."],
    tags: ["passive", "countability", "prepositions"],
    level: 3,
    note: "「〜向け」は for。総称の複数形 beginners に冠詞は付けない。",
  },
  {
    id: "a20",
    ja: "私が言いたいのは、時間が足りないということです。",
    answers: [
      "What I want to say is that we do not have enough time.",
      "My point is that we don't have enough time.",
    ],
    tags: ["relative", "subordinate", "quantifier"],
    level: 3,
    note: "「私が言いたいのは」は what 節。補語は that 節。",
  },
  {
    id: "a21",
    ja: "彼女は病気だったにもかかわらず会議に出席しました。",
    answers: [
      "Although she was sick, she attended the meeting.",
      "She attended the meeting even though she was sick.",
    ],
    tags: ["subordinate", "verb-choice"],
    level: 3,
    note: "attend は前置詞不要。despite は前置詞なので節を続けられない。",
  },
  {
    id: "a22",
    ja: "東京に着くまでに3時間かかりました。",
    answers: ["It took three hours to get to Tokyo.", "It took us three hours to reach Tokyo."],
    tags: ["formal-subject", "infinitive-gerund"],
    level: 3,
    note: "所要時間は It takes ... to do。reach は前置詞を取らない。",
  },
  {
    id: "a23",
    ja: "この写真を見ると、子どものころを思い出します。",
    answers: [
      "This picture reminds me of my childhood.",
      "This photo reminds me of when I was a child.",
    ],
    tags: ["verb-choice", "prepositions"],
    level: 3,
    note: "remind A of B。主語を「写真」にすると英語らしくなる。",
  },
  {
    id: "a24",
    ja: "私は彼の意見に賛成できません。",
    answers: ["I cannot agree with his opinion.", "I don't agree with him."],
    tags: ["verb-choice", "prepositions", "modal"],
    level: 3,
    note: "agree は自動詞。人・意見には with、提案には to。",
  },
  {
    id: "a25",
    ja: "彼女は3人の子どもの世話をしなければなりません。",
    answers: [
      "She has to take care of three children.",
      "She must look after three children.",
    ],
    tags: ["modal", "verb-choice"],
    level: 3,
    note: "「世話をする」は take care of / look after。child の複数形は children。",
  },
  {
    id: "a26",
    ja: "もっと多くの人がこの問題に関心を持つべきです。",
    answers: [
      "More people should be interested in this problem.",
      "More people should care about this issue.",
    ],
    tags: ["quantifier", "modal", "passive"],
    level: 3,
    note: "「もっと多くの人」は more people。関心は be interested in。",
  },
  {
    id: "a27",
    ja: "彼が来られないとしたら、代わりに私が行きます。",
    answers: ["If he cannot come, I will go instead.", "If he can't make it, I'll go instead."],
    tags: ["conditional", "modal"],
    level: 3,
    note: "現実にありうる条件なので if + 現在形、主節は will。",
  },
  {
    id: "a28",
    ja: "英語を話すときは間違いを恐れる必要はありません。",
    answers: [
      "You do not have to be afraid of making mistakes when you speak English.",
      "You don't need to be afraid of making mistakes when speaking English.",
    ],
    tags: ["modal", "infinitive-gerund", "prepositions"],
    level: 3,
    note: "不要は don't have to。must not は「してはいけない」で意味が変わる。",
  },
  {
    id: "a29",
    ja: "彼が戻ってくるまで、ここで待っていましょう。",
    answers: ["Let's wait here until he comes back.", "Why don't we wait here until he returns?"],
    tags: ["request", "subordinate", "tense"],
    level: 3,
    note: "提案は Let's / Why don't we。until 節は現在形。",
  },
  {
    id: "a30",
    ja: "その本を読み終えるのに1週間かかりました。",
    answers: [
      "It took me a week to finish reading the book.",
      "It took me one week to read the book.",
    ],
    tags: ["formal-subject", "infinitive-gerund", "perfect"],
    level: 3,
    note: "finish の後ろは動名詞。to finish to read とはしない。",
  },
];
