import type { ComposePrompt } from "../types";

/**
 * レベル1（基礎）。
 *
 * 1文が短く、試している文法がひとつに絞れる問題だけを置く。ここでつまずく
 * タグは、上のレベルでも必ず足を引っ張るので、弱点分析の土台になる。
 *
 * `answers` は「これも正解にしたい」という別解を並べる。AI採点はここに
 * 無い言い回しも文脈で正解にできるが、AIが使えない環境（APIキー未設定・
 * 通信失敗）ではこの配列との照合だけが頼りになるため、自然な言い換えを
 * 2つ目まで書いておく。
 */
export const BASIC_PROMPTS: ComposePrompt[] = [
  {
    id: "b01",
    ja: "私は毎朝コーヒーを飲みます。",
    answers: ["I drink coffee every morning."],
    tags: ["tense", "agreement"],
    level: 1,
    note: "習慣は現在形。every morning に引かれて進行形にしない。",
  },
  {
    id: "b02",
    ja: "彼は今、宿題をしています。",
    answers: ["He is doing his homework now.", "He's doing his homework now."],
    tags: ["progressive", "countability"],
    level: 1,
    note: "いま進行中の動作は be + -ing。homework は不可算で複数形にしない。",
  },
  {
    id: "b03",
    ja: "私はもう昼食を食べました。",
    answers: ["I have already had lunch.", "I have already eaten lunch."],
    tags: ["perfect"],
    level: 1,
    note: "already は have と過去分詞の間に置く。",
  },
  {
    id: "b04",
    ja: "彼女は3年間ここで働いています。",
    answers: [
      "She has worked here for three years.",
      "She has been working here for three years.",
    ],
    tags: ["perfect", "prepositions"],
    level: 1,
    note: "継続は現在完了。期間には for、起点には since。",
  },
  {
    id: "b05",
    ja: "机の上にリンゴが1つあります。",
    answers: ["There is an apple on the desk."],
    tags: ["formal-subject", "articles", "prepositions"],
    level: 1,
    note: "「〜がある」は There is/are。接している面の上は on。",
  },
  {
    id: "b06",
    ja: "私は昨日、駅で彼に会いました。",
    answers: ["I met him at the station yesterday.", "I saw him at the station yesterday."],
    tags: ["tense", "prepositions"],
    level: 1,
    note: "点として捉える場所は at。yesterday があるので過去形。",
  },
  {
    id: "b07",
    ja: "この本は私には難しすぎます。",
    answers: ["This book is too difficult for me.", "This book is too hard for me."],
    tags: ["prepositions", "comparison"],
    level: 1,
    note: "「〜には」は for + 人。too は形容詞の前。",
  },
  {
    id: "b08",
    ja: "彼は英語を話すのが上手です。",
    answers: ["He is good at speaking English.", "He speaks English well."],
    tags: ["infinitive-gerund", "prepositions"],
    level: 1,
    note: "前置詞 at の後ろは動名詞。to speak とは言わない。",
  },
  {
    id: "b09",
    ja: "私は音楽を聴くのが好きです。",
    answers: ["I like listening to music.", "I like to listen to music."],
    tags: ["infinitive-gerund", "verb-choice"],
    level: 1,
    note: "listen は to が必要。hear（聞こえる）とは別の動詞。",
  },
  {
    id: "b10",
    ja: "窓を開けてもいいですか。",
    answers: ["May I open the window?", "Can I open the window?"],
    tags: ["request", "modal"],
    level: 1,
    note: "許可を求めるのは May I / Can I。Could you は相手への依頼。",
  },
  {
    id: "b11",
    ja: "手伝ってくれませんか。",
    answers: ["Could you help me?", "Can you help me?", "Would you help me?"],
    tags: ["request", "modal"],
    level: 1,
    note: "依頼は Could you ...?。目的語の me を落とさない。",
  },
  {
    id: "b12",
    ja: "私たちはそのニュースに驚きました。",
    answers: ["We were surprised at the news.", "We were surprised by the news."],
    tags: ["passive", "prepositions"],
    level: 1,
    note: "感情は受動態で表す。surprise は「驚かせる」という他動詞。",
  },
  {
    id: "b13",
    ja: "この写真は私の父が撮りました。",
    answers: ["This picture was taken by my father.", "My father took this picture."],
    tags: ["passive", "tense"],
    level: 1,
    note: "「この写真は」を主語にするなら受動態。take の過去分詞は taken。",
  },
  {
    id: "b14",
    ja: "彼女は私より速く走ります。",
    answers: ["She runs faster than I do.", "She runs faster than me."],
    tags: ["comparison", "agreement"],
    level: 1,
    note: "比較級 faster + than。主語が三人称単数なので runs。",
  },
  {
    id: "b15",
    ja: "富士山は日本で一番高い山です。",
    answers: ["Mt. Fuji is the highest mountain in Japan."],
    tags: ["comparison", "articles"],
    level: 1,
    note: "最上級には the。範囲は in Japan。",
  },
  {
    id: "b16",
    ja: "私には兄が2人います。",
    answers: ["I have two brothers.", "I have two older brothers."],
    tags: ["verb-choice", "countability"],
    level: 1,
    note: "家族が「いる」は have。There are two brothers... とは言わない。",
  },
  {
    id: "b17",
    ja: "水を少しいただけますか。",
    answers: ["Could I have some water?", "Can I have some water?"],
    tags: ["quantifier", "countability", "request"],
    level: 1,
    note: "water は不可算。a water ではなく some water。",
  },
  {
    id: "b18",
    ja: "私には宿題がたくさんあります。",
    answers: ["I have a lot of homework.", "I have a lot of homework to do."],
    tags: ["quantifier", "countability"],
    level: 1,
    note: "homework は不可算なので many homeworks とは言わない。",
  },
  {
    id: "b19",
    ja: "彼はたいてい電車で通学します。",
    answers: ["He usually goes to school by train."],
    tags: ["word-order", "prepositions"],
    level: 1,
    note: "頻度の副詞は一般動詞の前。交通手段は by + 無冠詞の名詞。",
  },
  {
    id: "b20",
    ja: "今日は雨が降っていません。",
    answers: ["It is not raining today.", "It isn't raining today."],
    tags: ["progressive", "formal-subject"],
    level: 1,
    note: "天気の主語は it。今の状況なので進行形。",
  },
  {
    id: "b21",
    ja: "私は明日、京都を訪れる予定です。",
    answers: ["I am going to visit Kyoto tomorrow.", "I will visit Kyoto tomorrow."],
    tags: ["tense", "modal"],
    level: 1,
    note: "決めてある予定は be going to。visit は前置詞を取らない。",
  },
  {
    id: "b22",
    ja: "彼が来るかどうか分かりません。",
    answers: ["I don't know whether he will come.", "I don't know if he will come."],
    tags: ["subordinate", "word-order"],
    level: 1,
    note: "「〜かどうか」は whether / if。ここでの if 節は未来形のままでよい。",
  },
  {
    id: "b23",
    ja: "彼女がどこに住んでいるか知っていますか。",
    answers: ["Do you know where she lives?"],
    tags: ["word-order", "subordinate"],
    level: 1,
    note: "間接疑問は〈疑問詞＋主語＋動詞〉。where does she live とはしない。",
  },
  {
    id: "b24",
    ja: "私は彼に電話するのを忘れました。",
    answers: ["I forgot to call him."],
    tags: ["infinitive-gerund"],
    level: 1,
    note: "forget to do は「これからすることを忘れる」。forgot calling は「電話したことを忘れる」。",
  },
  {
    id: "b25",
    ja: "彼は医者になりたいと言っています。",
    answers: ["He says that he wants to be a doctor.", "He says he wants to be a doctor."],
    tags: ["subordinate", "articles"],
    level: 1,
    note: "職業には a を付ける。that は省略できる。",
  },
  {
    id: "b26",
    ja: "ドアを閉めていただけますか。",
    answers: ["Could you close the door?", "Would you close the door?"],
    tags: ["request"],
    level: 1,
    note: "Please close the door. より Could you ...? のほうが丁寧。",
  },
  {
    id: "b27",
    ja: "彼らは私を待ってくれました。",
    answers: ["They waited for me."],
    tags: ["verb-choice", "prepositions"],
    level: 1,
    note: "wait は自動詞。「〜を待つ」は wait for。",
  },
  {
    id: "b28",
    ja: "私は8時に家を出ました。",
    answers: ["I left home at eight.", "I left home at eight o'clock."],
    tags: ["verb-choice", "prepositions"],
    level: 1,
    note: "leave home は前置詞なし。時刻には at。",
  },
  {
    id: "b29",
    ja: "この電車は東京に行きますか。",
    answers: ["Does this train go to Tokyo?"],
    tags: ["word-order", "agreement"],
    level: 1,
    note: "疑問文で Does を使ったら、動詞は原形 go に戻す。",
  },
  {
    id: "b30",
    ja: "彼女は10年間ピアノを弾いています。",
    answers: [
      "She has played the piano for ten years.",
      "She has been playing the piano for ten years.",
    ],
    tags: ["perfect", "articles"],
    level: 1,
    note: "楽器には the。継続は現在完了。",
  },
];
