import type { ComposePrompt } from "../types";

/**
 * レベル2（標準）。
 *
 * 節がひとつ増える、あるいは2つの文法が同時に必要になる問題。
 * 基礎で個別にできていたことが、文が長くなった途端に崩れるかどうかを見る。
 */
export const STANDARD_PROMPTS: ComposePrompt[] = [
  {
    id: "s01",
    ja: "私が家に着いたとき、母はもう夕食を作り終えていました。",
    answers: [
      "When I got home, my mother had already finished cooking dinner.",
      "My mother had already finished making dinner when I got home.",
    ],
    tags: ["perfect", "subordinate"],
    level: 2,
    note: "過去のある時点より前の出来事は過去完了（had + 過去分詞）。",
  },
  {
    id: "s02",
    ja: "彼は10年間ここに住んでいるので、この街をよく知っています。",
    answers: [
      "He has lived here for ten years, so he knows this city well.",
      "Since he has lived here for ten years, he knows this city well.",
    ],
    tags: ["perfect", "subordinate", "progressive"],
    level: 2,
    note: "know は状態動詞なので進行形にしない。",
  },
  {
    id: "s03",
    ja: "向こうで写真を撮っている女性は私の姉です。",
    answers: [
      "The woman taking pictures over there is my sister.",
      "The woman who is taking pictures over there is my sister.",
    ],
    tags: ["participle", "relative"],
    level: 2,
    note: "能動の意味で名詞を後ろから説明するときは -ing。",
  },
  {
    id: "s04",
    ja: "これは私が昨日買った本です。",
    answers: ["This is the book I bought yesterday.", "This is the book that I bought yesterday."],
    tags: ["relative", "articles"],
    level: 2,
    note: "目的格の関係代名詞は省略できる。特定できる本なので the。",
  },
  {
    id: "s05",
    ja: "彼が言ったことは本当ではありませんでした。",
    answers: ["What he said was not true.", "What he said wasn't true."],
    tags: ["relative", "agreement"],
    level: 2,
    note: "「〜したこと」は what 節。主語になると単数扱い。",
  },
  {
    id: "s06",
    ja: "英語を上達させるには、毎日書くことが大切です。",
    answers: [
      "It is important to write every day to improve your English.",
      "Writing every day is important to improve your English.",
    ],
    tags: ["formal-subject", "infinitive-gerund"],
    level: 2,
    note: "「〜するのは…だ」は It is ... to do の形式主語で書ける。",
  },
  {
    id: "s07",
    ja: "母は私に部屋を掃除させました。",
    answers: ["My mother made me clean my room."],
    tags: ["causative"],
    level: 2,
    note: "make + 人 + 動詞の原形。to clean とはしない。",
  },
  {
    id: "s08",
    ja: "先生は私たちに辞書を使わせてくれました。",
    answers: ["The teacher let us use dictionaries.", "Our teacher let us use a dictionary."],
    tags: ["causative", "countability"],
    level: 2,
    note: "許可の「〜させてくれる」は let + 人 + 原形。",
  },
  {
    id: "s09",
    ja: "私は彼が部屋に入るのを見ました。",
    answers: ["I saw him enter the room.", "I saw him entering the room."],
    tags: ["causative", "word-order"],
    level: 2,
    note: "知覚動詞のあとは原形か -ing。to enter とはしない。",
  },
  {
    id: "s10",
    ja: "もっと早く出発すれば、渋滞を避けられます。",
    answers: [
      "If we leave earlier, we can avoid the traffic.",
      "If you leave earlier, you can avoid traffic jams.",
    ],
    tags: ["conditional", "subordinate", "comparison"],
    level: 2,
    note: "条件の if 節では、未来のことでも現在形で書く。",
  },
  {
    id: "s11",
    ja: "もし私があなたなら、その仕事を引き受けます。",
    answers: ["If I were you, I would take the job.", "If I were you, I would accept the offer."],
    tags: ["conditional"],
    level: 2,
    note: "事実に反する仮定は If + 過去形（were）+ would。",
  },
  {
    id: "s12",
    ja: "この問題は思ったほど難しくありませんでした。",
    answers: [
      "This question was not as difficult as I had expected.",
      "This problem wasn't as difficult as I expected.",
    ],
    tags: ["comparison", "perfect"],
    level: 2,
    note: "「〜ほど…ない」は not as ... as。as の後ろは同じ形にそろえる。",
  },
  {
    id: "s13",
    ja: "東京の人口は大阪の人口より多い。",
    answers: [
      "The population of Tokyo is larger than that of Osaka.",
      "Tokyo has a larger population than Osaka.",
    ],
    tags: ["comparison", "verb-choice"],
    level: 2,
    note: "人口の多い少ないは large / small。比べる相手は that of ... でそろえる。",
  },
  {
    id: "s14",
    ja: "彼は私が知っている中で最も親切な人です。",
    answers: ["He is the kindest person I know.", "He is the kindest person that I know."],
    tags: ["comparison", "relative"],
    level: 2,
    note: "最上級 + 関係代名詞。I know は現在形でよい。",
  },
  {
    id: "s15",
    ja: "その計画は次の会議で議論されるでしょう。",
    answers: ["The plan will be discussed at the next meeting."],
    tags: ["passive", "modal", "verb-choice"],
    level: 2,
    note: "will + be + 過去分詞。discuss は about を取らない。",
  },
  {
    id: "s16",
    ja: "彼の車は昨日盗まれました。",
    answers: ["His car was stolen yesterday."],
    tags: ["passive", "tense"],
    level: 2,
    note: "誰が盗んだか言わないので受動態。steal の過去分詞は stolen。",
  },
  {
    id: "s17",
    ja: "私は宿題を終えてからテレビを見ました。",
    answers: [
      "After I finished my homework, I watched TV.",
      "I watched TV after finishing my homework.",
    ],
    tags: ["subordinate", "infinitive-gerund"],
    level: 2,
    note: "after は接続詞にも前置詞にもなる。前置詞なら後ろは動名詞。",
  },
  {
    id: "s18",
    ja: "雨が降り出す前に家に着きたい。",
    answers: [
      "I want to get home before it starts to rain.",
      "I want to get home before it starts raining.",
    ],
    tags: ["subordinate", "tense"],
    level: 2,
    note: "時の副詞節では未来のことも現在形。before it will rain とはしない。",
  },
  {
    id: "s19",
    ja: "彼女は日本語だけでなく中国語も話せます。",
    answers: [
      "She can speak not only Japanese but also Chinese.",
      "She speaks not only Japanese but also Chinese.",
    ],
    tags: ["word-order", "modal"],
    level: 2,
    note: "not only A but also B の A と B は同じ品詞でそろえる。",
  },
  {
    id: "s20",
    ja: "私はその映画を3回見たことがあります。",
    answers: ["I have seen the movie three times.", "I have watched the movie three times."],
    tags: ["perfect", "quantifier"],
    level: 2,
    note: "経験の回数は現在完了 + 回数。I saw it three times は「いつ」が要る。",
  },
  {
    id: "s21",
    ja: "駅までの道を教えてくださいませんか。",
    answers: [
      "Could you tell me the way to the station?",
      "Could you show me the way to the station?",
    ],
    tags: ["request", "verb-choice"],
    level: 2,
    note: "道案内は teach ではなく tell / show。",
  },
  {
    id: "s22",
    ja: "彼はその知らせを聞いて喜びました。",
    answers: ["He was glad to hear the news.", "He was happy to hear the news."],
    tags: ["infinitive-gerund", "passive"],
    level: 2,
    note: "感情の原因は to do で表す。because he heard ... でもよい。",
  },
  {
    id: "s23",
    ja: "私の家族はみんな早起きです。",
    answers: [
      "Everyone in my family gets up early.",
      "All the members of my family get up early.",
    ],
    tags: ["agreement", "quantifier"],
    level: 2,
    note: "everyone は単数扱いなので gets。",
  },
  {
    id: "s24",
    ja: "生徒の半分以上がその本を読んでいます。",
    answers: [
      "More than half of the students have read the book.",
      "Over half of the students have read the book.",
    ],
    tags: ["quantifier", "agreement", "perfect"],
    level: 2,
    note: "half of the + 複数名詞は複数扱い。of the を落とさない。",
  },
  {
    id: "s25",
    ja: "この街には見るべきものがたくさんあります。",
    answers: [
      "There are a lot of things to see in this city.",
      "There are many things to see in this city.",
    ],
    tags: ["formal-subject", "infinitive-gerund", "quantifier"],
    level: 2,
    note: "名詞を後ろから説明する to do。things to see の語順に注意。",
  },
  {
    id: "s26",
    ja: "彼に会うのは久しぶりです。",
    answers: [
      "I haven't seen him for a long time.",
      "It has been a long time since I last saw him.",
    ],
    tags: ["perfect", "formal-subject"],
    level: 2,
    note: "「久しぶり」は現在完了の否定か It has been ... since で表す。",
  },
  {
    id: "s27",
    ja: "彼女はそのニュースに興味があるようです。",
    answers: [
      "She seems to be interested in the news.",
      "It seems that she is interested in the news.",
    ],
    tags: ["passive", "prepositions", "formal-subject"],
    level: 2,
    note: "be interested in は受動態の形。前置詞は in。",
  },
  {
    id: "s28",
    ja: "私は英語を勉強するために毎朝30分早く起きます。",
    answers: [
      "I get up thirty minutes earlier every morning to study English.",
      "I wake up thirty minutes early every morning to study English.",
    ],
    tags: ["infinitive-gerund", "comparison", "tense"],
    level: 2,
    note: "目的は to do。for studying とはしない。",
  },
  {
    id: "s29",
    ja: "その仕事を終えるのに、彼は3日かかりました。",
    answers: [
      "It took him three days to finish the work.",
      "It took him three days to complete the task.",
    ],
    tags: ["formal-subject", "infinitive-gerund"],
    level: 2,
    note: "「時間がかかる」は It takes + 人 + 時間 + to do。",
  },
  {
    id: "s30",
    ja: "誰も彼がなぜ辞めたのか知りません。",
    answers: ["Nobody knows why he quit.", "No one knows why he left the company."],
    tags: ["word-order", "agreement", "subordinate"],
    level: 2,
    note: "nobody は単数扱い。間接疑問なので why he quit の語順。",
  },
];
