-- 設定（苦手のしきい値・フラッシュ速度・発音のオンオフ）を同期するために
-- 足した列。本番へ適用済み。
--
-- その後、これらの設定は端末ごとに決まっているべきという判断で同期をやめた
-- （音量と同じ理由。PCと外出先のスマホで適切な値が違う）。アプリはこの列を
-- 読み書きしない。
--
-- 適用済みの履歴（supabase_migrations.schema_migrations）と食い違わせないため
-- ファイルは残し、列も drop しない。ベースラインの旧・モンスター収集の列と
-- 同じ扱い。null 許容の jsonb 1本なので、置いておく費用はない。
alter table user_meta add column if not exists settings jsonb;
